Repository sclorg/mariadb-container, pull requests merged in 2024-06, with the labels that each got.

#239 deprecate c8s images, as EOL for c8s is 31th of May 2024
  .github/workflows/build-and-push.yml
  .github/workflows/container-tests.yml
  10.11/.exclude-c8s
  10.11/root/usr/share/container-scripts/mysql/README.md
  10.3/.exclude-c8s
  10.3/root/usr/share/container-scripts/mysql/README.md
  10.5/.exclude-c8s
  10.5/root/usr/share/container-scripts/mysql/README.md
  README.md
  imagestreams/imagestreams.yaml
  imagestreams/mariadb-centos.json
Labels: ready for review

#243 Add file show_all_imagestreams.py from container-common-scripts
  imagestreams/imagestreams.yaml
  imagestreams/mariadb-rhel-aarch64.json
  imagestreams/mariadb-rhel.json
  test/show_all_imagestreams.py
Labels: ready for review, easyfix

#245 Add GitHub Action for Pytest
  .github/workflows/openshift-pytests.yml
Labels: enhancement, ready for review, easyfix

#242 Automatic update description on quay.io
  .github/workflows/build-and-push.yml
Labels: ready for review, easyfix
