Repository sclorg/mariadb-container, pull requests merged in 2025-04, with the labels that each got.

#268 [licensing] Add license specification for RHEL and CS images
  10.11/Dockerfile.c10s
  10.11/Dockerfile.c9s
  10.11/Dockerfile.rhel10
  10.11/Dockerfile.rhel9
  10.5/Dockerfile.c9s
  10.5/Dockerfile.rhel9
Labels: READY-to-MERGE, pr/needs-manual-merge

#271 [build resilience fix] Install DB packages via versioned names
  10.11/Dockerfile.fedora
  10.11/Dockerfile.rhel10
Labels: pr/needs-manual-merge

#272 Switch Ubuntu 20.04 to Ubuntu latest.
  .github/workflows/container-tests.yml
Labels: pr/missing-review
